### ISSUE TITLE
出现中文标点导致运行报错

### ISSUE THREAD

**Issue by Mateoust** [kosakarin/hoshino_big_cockroach#1]
以下140行和148行的冒号是中文
https://github.com/kosakarin/hoshino_big_cockroach/blob/3a3c3d625aca9fb57d3d133bc7665a266c8cbadd/randomtkk.py#L148
https://github.com/kosakarin/hoshino_big_cockroach/blob/3a3c3d625aca9fb57d3d133bc7665a266c8cbadd/randomtkk.py#L140
在150行的一个括号以及一个逗号是中文
https://github.com/kosakarin/hoshino_big_cockroach/blob/3a3c3d625aca9fb57d3d133bc7665a266c8cbadd/randomtkk.py#L150

**Comment by CYDXDianXian** [comment]
谢谢大神！我说怎么一顿报错呢

**Comment by kosakarin** [comment]
收到，当时本地代码改完了git上忘记修了，不好意思，等会修复

**Comment by kosakarin** [comment]
我说我本地怎么没报错，这几个地方是我git上现写的，写的时候没关输入法，本地没这两段，草（一种植物）
