### ISSUE TITLE
发送指令后出现了这些报错

### ISSUE THREAD

**Issue by 15220526** [kosakarin/hoshino_big_cockroach#3]
请问这是什么原因呢
![image](https://user-images.githubusercontent.com/106159640/198168167-57c5827a-53c3-4b71-a2ac-d0876be647b8.png)

**Comment by 15220526** [comment]
哦看了一下是下载的文件夹名字额代码里的路径不一样的，改一下就好了

**Comment by kosakarin** [comment]
阿哲 应该也是我的问题，当时写的时候偷懒了直接用了相对路径，有时间改改，感谢反馈
